### ISSUE TITLE
💡 [需求] 

### ISSUE THREAD

**Issue by Yan546** [Sevtinge/Cemiuiler#26]
### 需求内容

这个功能不动就是默认的？还是是被改过的，会和其它模块冲突吗？如果是默认的我觉得改成这样“3(默认)”比较好或者加个开关
![Screenshot_2023-04-23-21-30-50-469_com sevtinge cemiuiler-edit](https://user-images.githubusercontent.com/110469664/233842837-e9aea0f0-fdf0-4a82-93f0-c0d73e21bbf3.jpg)

### 简单例子

“3”改成“3(默认)”，或者加个开关

**Comment by Yan546** [comment]
因为我在用<MIUI原生通知图标>模块，里面有这个功能，但如果用其它模块改过的话会有bug

**Comment by Sevtinge** [comment]
加了~

**Comment by Yan546** [comment]
谢了
