### ISSUE TITLE
💡 [需求] 回弹动画修改

### ISSUE THREAD

**Issue by 2390768070** [Sevtinge/Cemiuiler#28]
### 需求内容

请将回弹动画做成可以调节的，就像miuihomer那样的，现在这个回弹动画太死板了，只有打开文件夹有回弹，关闭却没有，给人一种很违和的感觉

### 实现思路&截图

![Screenshot_2023-04-25-00-41-25-474_com yuk miuiHomeR](https://user-images.githubusercontent.com/131698308/234061545-bd8ceee7-a47c-4a14-8e81-62a95c7ea2ea.jpg)

### 简单例子

增加体验感

**Comment by Sevtinge** [comment]
加好了 但逻辑略有不同
